name: Test and Publish

on:
  pull_request_target:
    types:
      - closed
    branches:    
      - 'master'
defaults:
  run:
    shell: bash

env:
  GPR_USERNAME: ${{ secrets.GPR_USERNAME }}
  GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
  DOTNET_VERSION: 7.0.x

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET Core
      if: ${{ success() }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Test
      if: ${{ success() }}
      run: dotnet test

  build:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    env:
      LAST_COMMITTER_EMAIL: $(git log -1 --pretty=format:'%ae')
      BOT_TOKEN: secrets.BOT_ACCESS_TOKEN

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.BOT_ACCESS_TOKEN }}

    - name: Install .NET Core for Versionize
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.300

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      if: ${{ success() }}
      run: dotnet build --configuration Release

    - name: Increment Version
      if: ${{ success() }}
      run: |
        git remote set-url origin https://x-access-token:${{ env.BOT_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout "${GITHUB_REF:11}"
        dotnet tool install --global Versionize --version 1.8.0
        versionize --skip-dirty && git push --follow-tags origin "${GITHUB_REF:11}"

    - name: Pack
      if: ${{ success() }}
      run: dotnet pack --configuration Release -o output

    - name: Publish
      if: ${{ success() }}
      run: |
        dotnet --version
        dotnet nuget push "output/*.nupkg" \
          --source https://nuget.pkg.github.com/bornlogic/index.json \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          --skip-duplicate --no-symbols